[book]
title = "Study: Rust Programming Language 2nd edition"
authors = ["jerok-kim"]
language = "kr"
multilingual = true
src = "src"

[rust]
edition = "2021"

[build]
# github pages에서 main브랜치의 docs폴더를 deploy 하기 위해 변경
build-dir = "docs"
create-missing = true
use-default-preprocessors = true
extra-watch-dirs = []

[output.html]
default-theme = "Rust"
mathjax-support = true
git-repository-url = "https://github.com/jerok-kim/rust_lang_book"
git-repository-icon = "fa-github"

[output.html.playground]
editable = true
copyable = true
line-numbers = true
runnable = true